- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20220822144925_create_active_storage_tables.active_storage.rb
- db/schema.rb
Verifier l'installation de cloudinary please
> cloudinary connecte avec notre app

- app/controllers/games_controller.rb
- app/views/games/index.html.erb
- config/routes.rb
- test/controllers/games_controller_test.rb
Mis en place des routes pour games et booking
mise en place du controller games avec methode index
mise en place de la view games/index
> mise en place des routes et games index

- Gemfile.lock
- app/models/user.rb
> Validate uniqueness email

- app/controllers/games_controller.rb
> Gamescontroller

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
verifier setup des views devise
> devise views setup

- app/controllers/booking_controller.rb
- test/controllers/booking_controller_test.rb
> booking controller

- app/controllers/application_controller.rb
- app/controllers/games_controller.rb
Vérifier la mise en place du before action
> before action setup

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
ajout first name last name formulaires de registration
> Registrations views

- app/controllers/games_controller.rb
> fichier view new et show de games

- app/views/shared/_navbar.html.erb
liens inscription/connexion dans la navbar
restera la lien vers le formulaire de création
> links user in navbar

- app/controllers/games_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
> conflit navbar resolu

- app/controllers/games_controller.rb
- app/views/games/new.html.erb
add input in views game + change g to G in Game controller
> views-game-new

- app/controllers/booking_controller.rb
Vérifier le controller booking please
> booking controller v1

- app/assets/stylesheets/components/_form_new_game.scss
- app/views/games/new.html.erb
update input views > games > new
> change input

- config/routes.rb
Vérifier la route de dashboard
> route de dashboard

- app/views/games/new.html.erb
add route in input views > games > new
> Route input

- app/views/shared/_navbar.html.erb
Add route : "ajouter un jeu" ---> new_game_path
> add route to proposer un jeu

- app/views/pages/dashboard.html.erb
> dashboard view

- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/games/index.html.erb
> front suite

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form_new_game.scss
- app/assets/stylesheets/components/_show_game.scss
- app/views/games/new.html.erb
> front modifications et renaùing class container

- app/assets/stylesheets/components/_home.scss
- app/views/games/index.html.erb
> front encore

- app/assets/stylesheets/components/_home.scss
- app/views/games/index.html.erb
> nouveau logo sur index

- app/assets/stylesheets/components/_buttons.SCSS
- app/assets/stylesheets/components/_index.scss
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
J'ai traduit le formulaire en français 
Pimpé les boutons
Mis en forme le formulaire
> input session new

- Gemfile
- Gemfile.lock
- app/controllers/games_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/models/game.rb
- app/views/layouts/application.html.erb
- config/initializers/geocoder.rb
- db/migrate/20220824090057_add_coordinates_to_games.rb
- db/schema.rb
J'ai installé gem geocoder et tout le setup
> geocoder install

- app/assets/stylesheets/components/_home.scss
- app/views/games/index.html.erb
Add user last name in cards of games
> add user name

- app/controllers/bookings_controller.rb
- app/controllers/games_controller.rb
- app/views/bookings/new.html.erb
- app/views/games/show.html.erb
- config/routes.rb
> carrection scss

- app/views/devise/sessions/new.html.erb
- app/views/pages/dashboard.html.erb
> coucou mathieu

- app/assets/stylesheets/components/_form_new_game.scss
- app/assets/stylesheets/components/_show_game.scss
- app/views/games/new.html.erb
- app/views/games/show.html.erb
liens accueil plus bouton réserver sur la show d'un jeu
> front show btn booking + link home

- app/controllers/bookings_controller.rb
- app/controllers/games_controller.rb
- app/views/games/index.html.erb
La card disparait quand réservée
> game update

- app/assets/stylesheets/components/_form_new.scss
- app/assets/stylesheets/components/_index.scss
- app/views/bookings/new.html.erb
- app/views/games/new.html.erb
font sur le booking formulaire
> font sur le booking formulaire

- app/controllers/games_controller.rb
- app/views/games/index.html.erb
- app/views/pages/dashboard.html.erb
- db/migrate/20220824134930_change_disponibility_to_game.rb
- db/schema.rb
> gestion dispo de annonces

- db/seeds.rb
ajout d'une ville dans l'adresse des seeds
> vraies villes adresses seeds

- app/assets/stylesheets/components/_home.scss
- app/controllers/games_controller.rb
- app/javascript/controllers/address_autocomplete_controller.js
- app/views/games/index.html.erb
- app/views/pages/dashboard.html.erb
> search-bar

- app/views/devise/registrations/new.html.erb
> front formulaire sign up

- app/javascript/plugins/flatpickr.js
- app/views/bookings/new.html.erb
> calendrier inline

- app/javascript/application.js
ajout de l'auto reload sur le calendrier
> auto reload du calendrier

- db/seeds.rb
Ajout de vraies adresses dans la seed pour la map :
3 à Marseille
1 à Toulon 
1 à Aix-en-Provence
Pour que la carte ne soit pas trop grande et qu'on puisse faire une recherche par ville
> vraies-adresses

- app/assets/stylesheets/components/_home.scss
J'ai mi du border-radius uniquement sur le haut de la photo pour les cards des games dans l'index
> border-radius

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_home.scss
- app/views/pages/dashboard.html.erb
> correction-dashboard

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> new navbar with username

- app/views/games/index.html.erb
> traduction

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_show.scss
- app/views/games/show.html.erb
> footer en bas

- app/assets/stylesheets/components/_dashboard.scss
- app/views/pages/dashboard.html.erb
> add-anonce
